### ISSUE TITLE
two-point georegistration from shiny click

### ISSUE THREAD

**Issue by mdsumner** [ropenscilabs/geoflowr#1]
I traced this out using `affinething` - appreciate the shiny example, this could be worked up into a neat application!

```R
library(raster)
r <- brick("inst/shiny/image_click/world.png")

## click southwest, then northwest 
## (I chose the gridline intersections west of SAmerica ,and NULL island)
## note that shiny returns the pixel count from the top, so nrow - y
## these values are reported by the shiny app on screen currently
xy <- rbind(c(x = 194, y = nrow(r) - 416),
c(x = 490, y = nrow(r) - 292))

## those locations are these coordinates, the grid line intersections 
pts <- rbind(c(x = -120, -50), 
             c(x = 0, 0))

rfix  <- setExtent(r, affinething::domath(pts, xy, r = r))
plotRGB(rfix)
maps::map(add = TRUE)
points(pts)
```

![image](https://user-images.githubusercontent.com/4107631/49013379-aba4dc80-f1d0-11e8-97bc-a8f22c220814.png)

**Comment by mrjoh3** [comment]
![georef](https://user-images.githubusercontent.com/1921793/49048309-5d262b00-f22e-11e8-815c-67fd73c7d6e5.png)

@mdsumner I merged your code into the shiny app and it works really well. This could work realy well once I have time to clean it up and do some error / quality checking and output the result properly.

**Comment by mdsumner** [comment]
Great!  I'm really excited to learn from the shiny development here, I find that really hard to do. 

I've been thinking about the various cases (I can provide examples too): 

* no click required, we know the xmin, xmax, ymin, ymax  and crs of the image, apply it
* 2-click, enter known coordinates (great for grid/graticule on map)
* 2-click on image, 2-click on known map (requires some user choice for context/region)
* 2-click, enter known long-lat (i.e. graticule labels) and crs of the image (project longlat to crs)
* 2-click, enter  known or 2-click easting-northing and crs of the image 


A super-feature that would really help is to be able to add live horizontal/vertical line intersecting the mouse point, so it can be lined up when the grid is obscured (as in this image). But, being able to click an known map on a feature like a peninsula is probably just as powerful.

**Comment by mrjoh3** [comment]
I have added a bunch of UI elements to make it look better. most of this still needs the server functions to be written. It does now display the corrected image which is good. I am having trouble with the map ckick though, some parts of the image do not appear to click. I will investigate.

**Comment by mrjoh3** [comment]
hi @mdsumner today I split the app into separate files server.R, ui.R and global.R. This does not make any difference with the functionality but make it easier to maintain as the codebase grows. Tonight I will switch the map backgrounds to leaflet. This will make it easier to add a graticule and to add the georeferenced output.

**Comment by mdsumner** [comment]
This issue was moved to mrjoh3/georefr#4
