### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/geoflowr#2]
@mrjoh3 @RPanczak @gabyd :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by mrjoh3** [comment]
Hi @maelle, I am happy for it to transfer to a personal account. @gabyd or @RPanczak please advise if you want it in your accounts, otherwise mine is fine.

Thanks

**Comment by maelle** [comment]
Thank you! I'll transfer it to yours and then you can transfer it again if that's fine. Please accept the transfer @mrjoh3 (it had to transit via my account because of GitHub rules on transfer from an organization).

**Comment by RPanczak** [comment]
Hi team. Sorry for late reply. Fine for me to transfer all to @mrjoh3 Thanks for handling that @maelle
